### ISSUE TITLE
concern about the error in the dataprep step

### ISSUE THREAD

**Issue by lyj95618** [GoekeLab/xpore#188]
Hi,

I am currently running the xpore dataprep step using Ensembl transcriptome fasta and GTF. Even though the jobs are still running in the cluster, I see some error messages popping out as below (just copied some of them):

```
/hpf/largeprojects/ccmbio/yliang/long_read_RNA/nanopore_brian/python_venv/lib/python3.9/site-packages/xpore/scripts/dataprep.py:21: PerformanceWarning: indexing past lexsor
t depth may impact performance.
  pos_end += eventalign_result.loc[index]['line_length'].sum()

Process Consumer-35:
Traceback (most recent call last):
  File "/hpf/tools/centos7/python/3.9.13/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/hpf/largeprojects/ccmbio/yliang/long_read_RNA/nanopore_brian/python_venv/lib/python3.9/site-packages/xpore/scripts/helper.py", line 113, in run
    result = self.task_function(*next_task_args,self.locks)
  File "/hpf/largeprojects/ccmbio/yliang/long_read_RNA/nanopore_brian/python_venv/lib/python3.9/site-packages/xpore/scripts/dataprep.py", line 419, in preprocess_gene
    genomic_coordinate = list(itemgetter(*zip(tx_ids,tx_positions))(t2g_mapping)) # genomic_coordinates -- np structured array of 'chr','gene_id','genomic_position','kmer'
KeyError: ('ENSMUST00000164213', 2571)
Process Consumer-20:
Traceback (most recent call last):
  File "/hpf/tools/centos7/python/3.9.13/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/hpf/largeprojects/ccmbio/yliang/long_read_RNA/nanopore_brian/python_venv/lib/python3.9/site-packages/xpore/scripts/helper.py", line 113, in run
    result = self.task_function(*next_task_args,self.locks)
  File "/hpf/largeprojects/ccmbio/yliang/long_read_RNA/nanopore_brian/python_venv/lib/python3.9/site-packages/xpore/scripts/dataprep.py", line 419, in preprocess_gene
    genomic_coordinate = list(itemgetter(*zip(tx_ids,tx_positions))(t2g_mapping)) # genomic_coordinates -- np structured array of 'chr','gene_id','genomic_position','kmer'
KeyError: ('ENSMUST00000168989', 2777)
Process Consumer-26:
Traceback (most recent call last):
  File "/hpf/tools/centos7/python/3.9.13/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/hpf/largeprojects/ccmbio/yliang/long_read_RNA/nanopore_brian/python_venv/lib/python3.9/site-packages/xpore/scripts/helper.py", line 113, in run
    result = self.task_function(*next_task_args,self.locks)
  File "/hpf/largeprojects/ccmbio/yliang/long_read_RNA/nanopore_brian/python_venv/lib/python3.9/site-packages/xpore/scripts/dataprep.py", line 419, in preprocess_gene
    genomic_coordinate = list(itemgetter(*zip(tx_ids,tx_positions))(t2g_mapping)) # genomic_coordinates -- np structured array of 'chr','gene_id','genomic_position','kmer'
KeyError: ('ENSMUST00000172859', 520)
```
I am wondering what this means and should I stop it and debug it? Meanwhile, I do see outputs are being written to the data.index, data.json, data.readcount, eventalign.index, and data.log files

My xpore command is:
```
xpore dataprep \
--eventalign /hpf/largeprojects/ccmbio/acelik_files/kalish/nanopore/nanopore/nanopolish_output/$sample.eventalign.txt \
--gtf_or_gff /hpf/largeprojects/ccmbio/acelik_files/genomes/species/Mus_musculus.GRCm38/annotations/Mus_musculus.GRCm38.95.gtf \
--transcript_fasta /hpf/largeprojects/ccmbio/acelik_files/genomes/species/Mus_musculus.GRCm38/Mus_musculus.GRCm38.cdna.all.fa \
--out_dir ./dataprep \
--n_processes 18 \
--genome
```

Thanks for the helps!

Laur

**Comment by yuukiiwa** [comment]
Hi Laur (@lyj95618),

Sorry for the delayed reply! This can happen if you use a different release of reference.fa here in xpore from your alignment and nanopolish eventalign. Please try using the same release of the reference.fa and annotation.gtf throughout the processing.

Thanks!

Best wishes,
Yuk Kei
