### ISSUE TITLE
diffmod error

### ISSUE THREAD

**Issue by rugilemat** [GoekeLab/xpore#216]
Hi,

I've run `f5c eventalign` and `xpore dataprep` without issues but I'm running into an error with `xpore diffmod`:

```
Traceback (most recent call last):
  File "/users/k19022845/.local/bin/xpore", line 8, in <module>
    sys.exit(main())
  File "/users/k19022845/.local/lib/python3.8/site-packages/xpore/scripts/xpore.py", line 67, in main
    options.func(options)
  File "/users/k19022845/.local/lib/python3.8/site-packages/xpore/scripts/diffmod.py", line 89, in diffmod
    data_info = config.get_data_info()
  File "/users/k19022845/.local/lib/python3.8/site-packages/xpore/diffmod/configurator.py", line 31, in get_data_info
    for condition_name, run_names in self.yaml['data'].items():
AttributeError: 'NoneType' object has no attribute 'items'
```

I'm running xpore on HPC with the following command:
```
project="/scratch/prj/ppn_microglia_mod/directrna/xpore/pilot"
xpore diffmod --n_processes 64 --config ${project}/xpore.yml

```

My yml file looks like:
```
data:
a_007:
rep1: /scratch/prj/ppn_microglia_mod/directrna/xpore/pilot/007
b_007_flush:
rep1: /scratch/prj/ppn_microglia_mod/directrna/xpore/pilot/007_flush
c_36S:
rep1: /scratch/prj/ppn_microglia_mod/directrna/xpore/pilot/36S

out: /scratch/prj/ppn_microglia_mod/directrna/xpore/pilot/xpore-pilot
```
The dataprep output files are not empty and are all there for each sample (data.index, data.json, data.log, data.readcount and eventalign.index).
Any advice would be appreciated!

**Comment by yuukiiwa** [comment]
Hi @rugilemat,

Can you try indenting your samples within the data section:
```
data:
    a_007:
        rep1: /scratch/prj/ppn_microglia_mod/directrna/xpore/pilot/007
    b_007_flush:
        rep1: /scratch/prj/ppn_microglia_mod/directrna/xpore/pilot/007_flush
    c_36S:
        rep1: /scratch/prj/ppn_microglia_mod/directrna/xpore/pilot/36S

out: /scratch/prj/ppn_microglia_mod/directrna/xpore/pilot/xpore-pilot
```

Thanks!

Best wishes,
Yuk Kei

**Comment by rugilemat** [comment]
Hi @yuukiiwa,

Thanks so much! When I indented the yml myself it threw out an error but copying this set up worked, thanks! Are you indenting with tab?

**Comment by yuukiiwa** [comment]
Hi @rugilemat,

I indented it with several spaces.

Best wishes,
Yuk Kei

**Comment by rugilemat** [comment]
Thanks for clarifying!
