### ISSUE TITLE
Not found in index error

### ISSUE THREAD

**Issue by callumparr** [GoekeLab/xpore#42]
I know have eventalign with correct headers but now there is another issue: 

```
Process Consumer-1:
Traceback (most recent call last):
  File "/opt/local/pyenv/versions/3.7.2/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/callum/.local/lib/python3.7/site-packages/xpore/scripts/helper.py", line 110, in run
    result = self.task_function(*next_task_args,self.locks)
  File "/home/callum/.local/lib/python3.7/site-packages/xpore/scripts/dataprep.py", line 79, in combine
    df2write = df_events_per_read.loc[[tx_id,read_id],:].reset_index()
  File "/home/callum/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 873, in __getitem__
    return self._getitem_tuple(key)
  File "/home/callum/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1044, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/home/callum/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 766, in _getitem_lowerdim
    return self._getitem_nested_tuple(tup)
  File "/home/callum/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 847, in _getitem_nested_tuple
    obj = getattr(obj, self.name)._getitem_axis(key, axis=axis)
  File "/home/callum/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1099, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/home/callum/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1037, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis, raise_missing=False)
  File "/home/callum/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1240, in _get_listlike_indexer
    indexer, keyarr = ax._convert_listlike_indexer(key)
  File "/home/callum/.local/lib/python3.7/site-packages/pandas/core/indexes/multi.py", line 2400, in _convert_listlike_indexer
    raise KeyError(f"{keyarr[mask]} not in index")
KeyError: "['f7099b1f-b12d-44d6-a477-1aaf478cadd5'] not in index"
```

I've tried installing latest version (0.5.6) but pip install gives error and latest I can install is 0.5.4. 

Additionally, would there be an issue where I only use fastq containing the pass reads (Q > 7). When I create nanopolish index I use the fast5 that contains all reads (inc. fail) but the fastq I have only contained Q>7. I assume this should not be an issue as just these reads will not end up in the eventalign file.

**Comment by zhongzhd** [comment]
i have a same error, have you resolved it?

**Comment by callumparr** [comment]
I had to install xpore 0.5.6 and specifically within a new python environment because xpore 0.5.6 is requires python 3.8. 

After this dataprep should proceed without any errors. 

If you are using an earlier version this could well be why you had this issue.
